In [3]:
def vector_matrix_product(mat, row, column,v):
    print('Given Matrix: ')
    for i in range(row):
        for j in range(column):
            print(mat[i][j],end=" ")
        print()
        
    print()
    print('Given Vector: ')
    for i in range(n):
        print(v[i],end=" ")
        print()

    print()
    

    for i in range(m): #row
        for j in range(n): #column
            mat[i][j] = mat[i][j] * v [j] 

    print('Matrix-Vector Product is: ')

    for i in range(m): #row
        for j in range(n): #column
            print(mat[i][j],end=" ")
        print()



In [4]:
 
m = int(input('Enter number of rows:'))
n = int(input('Enter number of columns:'))
matrix = []
vector = []

for i in range(0, m):
    c = []
    for j in range(0, n):
        j = int(input('Enter value for '+str(i)+ ' ' + str(j) + ': '))
        c.append(j)
    print()
    matrix.append(c)



for i in range(n):
    i = int(input('Enter vector value for '+str(i)))
    vector.append(i)
    print()


for i in range(0, m):
        for j in range(0, n):
            print(matrix[i][j],end=" ")
        print()

vector_matrix_product(matrix, m, n,vector)








1 2 3 
1 2 3 
1 2 3 
Given Matrix: 
1 2 3 
1 2 3 
1 2 3 

Given Vector: 
1 
2 
3 

Matrix-Vector Product is: 
1 4 9 
1 4 9 
1 4 9 


In [15]:
import numpy as np

#a = np.array([(1, 2, 3),(1, 2, 3),(1, 2, 3)]) # matrix m * n
#print(a)
#b = np.array([(2),(2),(2)]) # vector
#print(b)
row = 3
column = 3
a = np.arange(9).reshape(row, column)
b = np.arange(3).reshape(row, 1 )

print('Matrix: ')
print(a)
print()
print('Vector: ')
print(b)

# length = len(a)

for i in range(row):
    for j in range(column):
         a[i][j] = a[i][j] * b[j]
print()
print('Matrix vector product is: ')
for i in range(0, m):
        for j in range(0, n):
            print(a[i][j],end=" ")
        print()


Matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vector: 
[[0]
 [1]
 [2]]

Matrix vector product is: 
0 1 4 
0 4 10 
0 7 16 


In [31]:
a = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
b = np.array([[1],[2],[3]])

r,c = np.shape(a)

print('Matrix: ')
print(a)

print('Vector: ')
print(b)

#print(r)
#print(c)

for i in range(r):
    for j in range(c):
         a[i][j] = a[i][j] * b[j]

for i in range(r):
        for j in range(c):
            print(a[i][j],end=" ")
        print()

Matrix: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
Vector: 
[[1]
 [2]
 [3]]
1 4 9 
1 4 9 
1 4 9 


In [35]:
a = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
b = np.array([[1],[2],[3]])

product = a.dot(b)
product1 = a@b
product2 = np.matmul(a,b)
product3 = np.dot(a,b)

print()
print(product)

print()
print(product1)

print()
print(product2)

print()
print(product3)



[[14]
 [14]
 [14]]

[[14]
 [14]
 [14]]

[[14]
 [14]
 [14]]

[[14]
 [14]
 [14]]


In [16]:
import numpy as np
from scipy.sparse import csr_matrix

a = np.array([[1, 0, 3],[1, 2, 0],[0, 1, 3]])
b = np.array([[1],[2],[3]])

s = csr_matrix(a)

r,c = np.shape(s)
print()
print(s)
print(r)
print(c)

print()
print('Matrix vector product using for loop: ')
for i in range(r):
    #for j in range(c):
         s[i] = s[i] * b[i]


for i in range(r):
        #for j in range(c):
            print(s[i],end=" ")

print()
print('Matrix vector product without for loop: ')

product = a.dot(b)
print(product)
# print()
# b = s.todense()

# print(b)



  (0, 0)	1
  (0, 2)	3
  (1, 0)	1
  (1, 1)	2
  (2, 1)	1
  (2, 2)	3
3
3

Matrix vector product using for loop: 


ValueError: dimension mismatch